version: '3.8'

services:
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: jmeter
      INFLUXDB_HTTP_AUTH_ENABLED: "false"
    volumes:
      - influxdb-data:/var/lib/influxdb
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:10.4.2
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring

volumes:
  influxdb-data:
  grafana-data:

networks:
  monitoring:
    driver: bridge
